# Generated by Django 2.0.13 on 2020-07-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0023_auto_20200629_1440'),
        ('bidding', '0023_auto_20200602_1633'),
    ]

    operations = [
    ]
