# Generated by Django 2.0.4 on 2018-12-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0021_auto_20181126_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalposition',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='current_assignment',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='latest_bidcycle',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='post',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='tour_of_duty',
        ),
        migrations.DeleteModel(
            name='HistoricalPosition',
        ),
    ]
