version: '2'
services:
  data:
    image: alpine:3.4
    volumes:
      - /app
    command: /bin/true
    container_name: data
  app:
    image: talentmap/@@REPO_NAME@@:@@LABEL@@
    ports:
      - 8000:8000
    links:
      - db
      - data
    depends_on:
      - db
      - data
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    volumes_from:
      - data
    environment:
      - DJANGO_SECRET_KEY=development_secret_key
      - DATABASE_URL=postgres://talentmap-user@db/talentmap
      - DJANGO_DEBUG=true
  db:
    image: postgres:9.6.3
    container_name: db
    environment:
      - POSTGRES_DB=talentmap
      - POSTGRES_USER=talentmap-user
  mock_fsbid:
    image: metaphase/mock-fsbid
    links:
      - mock_db
    depends_on:
      - mock_db
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DB_HOST=mock_db
      - DB_NAME=mockfsbid
      - DB_USER=mockfsbid-user
      - DB_PASSWORD=fsbid_pwd
      - DB_PORT=5432
      - DB_CHARSET=utf8
      - DEBUG=false
      - DB_CLIENT=pg
  mock_db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_DB=mockfsbid
      - POSTGRES_USER=mockfsbid-user
      - POSTGRES_PASSWORD=fsbid_pwd
