version: '2'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    links:
      - oracle
    depends_on:
      - oracle
    # use this to run in https server locally
    # command: python manage.py runsslserver --certificate /app/talentmap_api/sp.crt --key /app/talentmap_api/sp.key 0.0.0.0:8000
    command: >
      bash -c "python show_logo.py
      && ./wait-for-oracle.sh oracle
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=development_secret_key
      - DATABASE_URL=oracle:1521/ORCLPDB1.localdomain
      - DATABASE_USER=talentmap
      - DATABASE_PW=newpassword
      - DJANGO_DEBUG=true
      - FSBID_API_URL=http://host.docker.internal:3333
      - EMPLOYEES_API_URL=http://host.docker.internal:3333/Employees
  oracle:
    ports:
      - 1521:1521
      - 32769:32769
    image: container-registry.oracle.com/database/enterprise
    volumes:
      - oracle:/var/lib/oracle/data/
    environment:
      - ORACLE_USER=talentmap
      - ORACLE_PW=newpassword
volumes:
  pgdata:
  oracle:
