version: '2'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    links:
      - oracle
    depends_on:
      - oracle
    # use this to run in https server locally
    # command: python manage.py runsslserver --certificate /app/talentmap_api/sp.crt --key /app/talentmap_api/sp.key 0.0.0.0:8000
    command: >
      bash -c "python show_logo.py
      && echo 'Starting...'
      && ./wait-for-oracle.sh oracle:1521/talentmap sys talentmap 'as sysdba'
      && echo exit | /opt/oracle/instantclient*/sqlplus -L -S sys/talentmap@//oracle:1521/talentmap as sysdba @create-oracle-user.sql
      && echo 'Oracle user created!'
      && ./wait-for-oracle.sh oracle:1521/talentmappdb talentmap1 talentmap1 '' true
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=development_secret_key
      - DATABASE_URL=oracle:1521/talentmappdb
      - DATABASE_USER=talentmap1
      - DATABASE_PW=talentmap1
      - DJANGO_DEBUG=true
      - FSBID_API_URL=http://host.docker.internal:3333
      - EMPLOYEES_API_URL=http://host.docker.internal:3333/Employees
      - CP_API_URL=http://host.docker.internal:3333/cyclePositions
  oracle:
    ports:
      - 1521:1521
    image: banglamon/oracle193db:19.3.0-ee
    volumes:
      - oracle:/var/lib/oracle/data/
    environment:
      - ORACLE_SID=talentmap
      - ORACLE_PDB=talentmappdb
      - ORACLE_PWD=talentmap
volumes:
  pgdata:
  oracle:
