version: '2'
services:
  app:
    links:
      - mock_fsbid
  mock_fsbid:
    image: metaphase/mock-fsbid
    links:
      - mock_db
    depends_on:
      - mock_db
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DB_HOST=db
      - DB_NAME=mockfsbid
      - DB_USER=mockfsbid-user
      - DB_PASSWORD=fsbid_pwd
      - DB_PORT=5432
      - DB_CHARSET=utf8

