# Generated by Django 2.0.4 on 2018-12-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_frontendsecrets_reportederror_reportedevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedevent',
            old_name='EnvironmentError',
            new_name='event',
        ),
    ]
