DECLARE
  v_userID AUTH_USER.ID%TYPE;
  v_groupID AUTH_GROUP.ID%TYPE;
BEGIN
  SELECT ID INTO v_userID FROM AUTH_USER WHERE EMAIL = 'EnlowZ_7@state.gov';
  SELECT ID INTO v_groupID FROM AUTH_GROUP WHERE NAME = 'superuser';
  INSERT INTO AUTH_USER_GROUPS(USER_ID, GROUP_ID) VALUES (v_userID, v_groupID);
  COMMIT;
END;